version: '3'
services:
  dns:
    build: ./dns
    image: docker_open5gs_dns
    container_name: dns
    volumes:
      - ./dns:/mnt/dns
    expose:
      - "53/udp"
    networks:
      default:
        ipv4_address: ${DNS_IP}
  mongo:
    build: ./mongo
    image: docker_open5gs_mongo
    container_name: mongo
    volumes:
      - ./mongo:/mnt/mongo
      - ./mongodb:/var/lib/mongodb
    ports:
      - "27017:27017"
    networks:
      default:
        ipv4_address: ${MONGO_IP}
  hss:
    build: ./hss
    image: docker_open5gs_hss
    container_name: hss
    volumes:
      - ./hss:/mnt/hss
      - ./log:/open5gs/install/var/log/open5gs
    environment:
      - MONGO_IP=${MONGO_IP}
      - MME_IP=${MME_IP}
      - DB_URI=mongodb://${MONGO_IP}/open5gs
    depends_on:
      - dns
      - mongo
    dns: ${DNS_IP}
    ports:
      - "3000:3000"
    networks:
      default:
        ipv4_address: ${HSS_IP}
  sgw:
    build: ./sgw
    image: docker_open5gs_sgw
    container_name: sgw
    volumes:
      - ./sgw:/mnt/sgw
      - ./log:/open5gs/install/var/log/open5gs
    depends_on:
      - dns
    dns: ${DNS_IP}
    ports:
      - "2152:2152/udp"
    networks:
      default:
        ipv4_address: ${SGW_IP}
  pgw:
    build: ./pgw
    image: docker_open5gs_pgw
    container_name: pgw
    volumes:
      - ./pgw:/mnt/pgw
      - ./log:/open5gs/install/var/log/open5gs
    environment:
      - PCRF_IP=${PCRF_IP}
    depends_on:
      - dns
    dns: ${DNS_IP}
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      default:
        ipv4_address: ${PGW_IP}
  mme:
    build: ./mme
    image: docker_open5gs_mme
    depends_on:
      - hss
      - sgw
      - pgw
    container_name: mme
    volumes:
      - ./mme:/mnt/mme
      - ./log:/open5gs/install/var/log/open5gs
    depends_on:
      - dns
    dns: ${DNS_IP}
#    ports:
#      - "36412:36412/sctp"
    environment:
      - HSS_IP=${HSS_IP}
      - SGW_IP=${SGW_IP}
      - PGW_IP=${PGW_IP}
    networks:
      default:
        ipv4_address: ${MME_IP}
  pcrf:
    build: ./pcrf
    image: docker_open5gs_pcrf
    container_name: pcrf
    depends_on:
      - mongo
      - dns
    dns: ${DNS_IP}
    volumes:
      - ./pcrf:/mnt/pcrf
      - ./log:/open5gs/install/var/log/open5gs
    environment:
      - PGW_IP=${PGW_IP}
      - MONGO_IP=${MONGO_IP}
    networks:
      default:
        ipv4_address: ${PCRF_IP}
networks:
  default:
    ipam:
      config:
        - subnet: ${SUBNET}
